name: 'Profane content filter'
description: 'When used on issues or pull requests, automatically filters out profanity.'

branding:
  icon: 'filter'
  color: 'red'

inputs:
  token:
    description:
      'The GitHub token used to update the issues or pull requests with. Example, secrets.GITHUB_TOKEN.'
    required: true
  replacement-strategy:
    description:
      'The type of replacement strategy to use when profane content is filtered. See https://github.com/IEvangelist/profanity-filter#-replacement-strategies.'
    required: false
    default: 'Asterisk'
  include-update-note:
    description:
      'Whether to include a note in the issue or pull request body indicating that the content was filtered.'
    required: false
    default: 'true'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/ievangelist/profanity-filter:latest'
