name: Dogfood

on:
  issue_comment:
  issues:
    types:
      - opened
      - edited
      - reopened
  pull_request:
    types:
      - opened
      - edited
      - reopened

jobs:
  filter:
    name: Apply profanity filter
    runs-on: ubuntu-latest
    permissions:
      # If the profane content label 
      # doesn't exist, this is required to create it.
      contents: write
      issues: write
      pull-requests: write

    steps:
    - name: Print actor
      run: |
        echo ${{ github.actor }}

    - name: Profanity filter
      if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'github-actions[bot]'  }}
      uses: IEvangelist/profanity-filter@main
      id: profanity-filter
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        replacement-strategy: first-letter-then-asterisk
